PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE time(
time_id INT PRIMARY KEY NOT NULL,
start_date DATETIME,
end_date DATETIME);
CREATE TABLE show(
show_id INT PRIMARY KEY NOT NULL,
name VARCHAR(90) NOT NULL,
id_time INT);
CREATE TABLE genre(
genre_id INT PRIMARY KEY NOT NULL,
genre1 VARCHAR(45),
genre2 VARCHAR(45),
genre3 VARCHAR(45));
CREATE TABLE story(
story_id INT PRIMARY KEY NOT NULL,
element1 VARCHAR(45),
element2 VARCHAR(45),
element3 VARCHAR(45));
CREATE TABLE theme(
theme_id INT PRIMARY KEY NOT NULL,
theme1 VARCHAR(45),
theme2 VARCHAR(45),
theme3 VARCHAR(45));
CREATE TABLE episode(
episode_id INT PRIMARY KEY NOT NULL,
name VARCHAR(90),
date DATETIME,
season TINYINT,
episode TINYINT,
id_show INT);
COMMIT;
